[versions]
commons = "2.0.2"
netcdf = "5.9.1"
guava = "33.5.0-jre"
slf4j = "2.0.17"
junit-jupiter = "6.0.1"

[libraries]
commons = { module = "io.github.stellarsunset:commons", version.ref = "commons" }
cdm-core = { module = "edu.ucar:cdm-core", version.ref = "netcdf" }

# Runtime dependencies supporting specific file formats
bufr = { module = "edu.ucar:bufr", version.ref = "netcdf" }
grib = { module = "edu.ucar:grib", version.ref = "netcdf" }
opendap = { module = "edu.ucar:opendap", version.ref = "netcdf" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
